### ISSUE TITLE
Design file server protocol (request and response payload format)

### ISSUE THREAD

**Issue by ldm2468** [ldm2468/cs536-project#11]
Design the protocol that the file server uses (i.e., the structure of request and response payloads). Things to consider: whether to use text-based or binary format, how to signal errors, etc.

For example, a text-based protocol may have payloads that look like this:
```json
{
    "action": "send",
    "filename": "hello.txt",
    "contents": "aGVsbG8gd29ybGQ"
}
```
while a binary format may use the python 'struct' module to pack fields in a compact manner. Fields that have a variable length, like file names, will have to be implemented carefully. Encoding the file list might be especially challenging.

 Issues #7, #8, #9, #10 depend on this.

**Comment by AnugunjNaman** [comment]
Fixed using Base64. See #14. Works for pdf, exe, text file.
